version: '3'

services:
  test:
    build: . # Build the image from the Dockerfile in the current directory
    volumes:
      - .:/app
    command: python3 -m pytest

  run:
    build: . # Build the image from the Dockerfile in the current directory
    volumes:
      - .:/app
    command: python3 main.py